
services:
  proxy:
    image: ubuntu/squid
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./squide.dev.conf:/etc/squid/squid.dev.conf
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - devnet
      - internet
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HTTP_PROXY=http://proxy:3128
      - HTTPS_PROXY=http://proxy:3128
    networks:
      - devnet
    depends_on:
      - proxy
    user: ubuntu
    working_dir: /home/ubuntu
    volumes:
      - ../:/home/ubuntu/workspace
      - ./.npmrc/:/home/ubuntu/.npmrc
    command: sleep infinity

  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - devnet
      - ingress_net
    ports:
      - "3000:3000"
networks:
  devnet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
  ingress_net:
    driver: bridge
